# Site settings
title: Code Nirvana
header-img: img/home-bg.png
email: keith.wellman@icloud.com
copyright_name: keithwellman
description: > # this means to ignore newlines until "baseurl:"
  A journey from Ruby to Full-Stack.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  keithwellman
learn_profile: keithwellman
email_username: keith.wellman@icloud.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
